version: "3.8"
services:
  tunnel:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${TOKEN}
    command: tunnel run 
networks:
  default:
    name: cloudflare
    external: true
